### ISSUE TITLE
cubic spline is not smooth

### ISSUE THREAD

**Issue by simonp0420** [tlycken/Interpolations.jl#108]
The following code results in a very jagged plot of the interpolated spline:

```
using Interpolations
using PyPlot
x = 1:5
y = sin(2*x)
itp = interpolate(y, BSpline(Cubic(Natural())), OnCell())
xi = linspace(1,5,200)
yi = Float64[itp[t] for t in xi]
plot(x,y,"ro")  # Plot the knots as red circles
plot(xi,yi)  # Plot the interpolated cubic spline
```

I understand that I'm under-sampling the sine function, but nevertheless I expected to get a smooth interpolant.  Plot is shown below.  Am I misunderstanding something or is this a bug?

Thanks,
--Peter

![figure_1](https://cloud.githubusercontent.com/assets/4294361/13659035/c91fd1dc-e631-11e5-8f7b-29aec6992ac5.png)

**Comment by timholy** [comment]
What happens with `OnGrid`? In general, the most natural formulation is `OnCell` for even orders and `OnGrid` for odd orders.

I wonder if we should make this the default, since I doubt we systematically support both `OnCell` and `OnGrid` for all possible combinations of orders and boundary conditions.

**Comment by simonp0420** [comment]
Here is the result for OnGrid:  The curve no longer interpolates the knots.
![figure_ongrid](https://cloud.githubusercontent.com/assets/4294361/13673346/7e17f1b8-e68d-11e5-8b0e-f232fc41d9ab.png)

**Comment by floswald** [comment]
very odd. I thought it might have to do with too few interpolatino points and an poorly-conditioned matrix. but with 20 points, the same. 
![figure_1](https://cloud.githubusercontent.com/assets/1021558/13674620/82d24e8c-e6de-11e5-92e5-7de99b948cc8.png)

**Comment by tlycken** [comment]
This is a bug, probably in the implementation of `prefiltering_system(::Type{T}, n, ::Cubic{Natural}, ::GT)`. I might be able to take a look at it this weekend, but you're very welcome to submit a patch if you find it before me :) 

Re: OnCell vs OnGrid, the distinction is only relevant to quadratic and higher for anything else than bounds-checking, and I don't think it's unrealistic to support both for the boundary conditions we implement. (We still need to improve the test suite, obviously...)

**Comment by tlycken** [comment]
What does `@which Interpolations.define_indices(BSpline{Cubic{Natural}}, 1,1)` say on your machine? What about `macroexpand(:( Interpolations.define_indices(BSpline{Cubic{Natural}}, 1,1)))`?

**Comment by tlycken** [comment]
@simonp0420, @floswald Also, if you do `Pkg.update()`, what does `Pkg.status()` say after that? Does it still reproduce?

On latest `master`, I can't reproduce this; my plots look fine both for `OnCell` and `OnGrid`. I wonder if this is just the problems hinted at in #99 which have been fixed on `master` but maybe not on your local copy.

**Comment by simonp0420** [comment]
```

julia> using Interpolations

julia> @which Interpolations.define_indices(BSpline{Cubic{Natural}}, 1,1)
define_indices{IT}(::Type{IT}, N, pad) at c:\home\simonp\.julia\v0.4\Interpolations\src\b-splines\indexing.jl:7

julia> macroexpand(:( Interpolations.define_indices(BSpline{Cubic{Natural}}, 1,1)))
:(Interpolations.define_indices(BSpline{Cubic{Natural}},1,1))
```

After a `Pkg.update()` there are no changes to anything but `NaNMath`.  `Pkg.status()` gives

```
...
 - Interpolations                0.3.4
...
```
and the problem persists.

**Comment by simonp0420** [comment]
After doing `Pkg.checkout("Interpolations")` the problem is gone for both `OnCell` and `OnGrid` :-)  Thanks for the tip.

**Comment by tlycken** [comment]
Time to tag a version, then :) Thanks for reporting back!

**Comment by floswald** [comment]
:+1:
