### ISSUE TITLE
Non-uniform interpolation

### ISSUE THREAD

**Issue by TheBB** [tlycken/Interpolations.jl#11]
I'm opening this issue based on [this discussion](https://github.com/TheBB/NURBS.jl/issues/5). I've looked at your source code relatively thoroughly, and I think I understand how it works, even though it's a bit more meta than I'm used to.

Am I correct in assuming that non-uniform interpolation is best represented as a new subtype of `GridRepresentation`, for example with knot vector as argument to the constructor?

If so, I'd like to start working on that, beginning with constants and working my way up.

**Comment by NateNesbitt** [comment]
Thanks for your work on this package - I'm excited for the non-uniform interpolation to be available! I'm new to GitHub, is this the proper place for a comment like this, or is there somewhere more appropriate for expressing interest in features like the package you're working on here?

Best,

Nate

**Comment by TheBB** [comment]
Here is fine. Unfortunately I had to start working on something rather different the last couple of months, so I haven't been able to dedicate time to this. :-(

**Comment by pwl** [comment]
I don't know if this is of any help but Fornberg [1] provides an algorithm for approximating derivatives (of any order) of a function given on a non-uniform 1d mesh.  In particular, it can be used to compute a value of a function (which is the zeroth-order derivative) at any given point (so not only at a mesh point).  The algorithm is pretty simple to implement and understand/modify, although I don't know if his approach can be generalized to tensor product grids.

[1] http://www.jstor.org/stable/2653239

**Comment by tlycken** [comment]
@pwl Thanks, that's a good reference. I don't have access to the article atm (the full article isn't available for free) but I can probably get access through my university. I will probably focus my efforts on getting the B-spline functionality (see #5) working, and stabilize the API (see #31), but I'll keep this in mind for the future if no-one else gets there before me :)

**Comment by tlycken** [comment]
I'm wondering if this can be considered solved in terms of `Gridded` (#56)...
