### ISSUE TITLE
Would be good if Interpolations played nicer with SharedArray

### ISSUE THREAD

**Issue by timday** [tlycken/Interpolations.jl#114]
I'm very new to Julia so apologies if I'm completely missing something obvious.  Please consider this an enhancement request.

I have a use-case where I want to have a bunch of worker processes use samples taken from an `interpolate` view of a large 3D SharedArray.  The access patterns aren't such that I can't split the array up using the distributed array type.  However, because `interpolate` seems to invariably make copies of the shared array (whether to pad the boundaries, or do some pre-filtering I'm not entirely sure) I seem to end up with each worker creating it's own non-shared copy of the same thing, which I don't have enough memory for.

A more detailed write-up with example code can be found at http://stackoverflow.com/questions/38663113/how-to-use-interpolations-on-sharedarray-in-worker-process-without-each-process

I've previously implemented this sort of thing in scipy where the shared array (possibly prefiltered for spline interpolation) can just be forked into the worker processes when a multiprocessing pool is created... but Julia's model seems to be a bit different.

Not sure what the ideal outcome looks like.  One of:
* If needed, some code/API change which makes this possible.
* Julia's 0.5 threading will likely make the issue go away as all the threads will presumably be able to hammer on single common `interpolate`, and no need for SharedArray.  Maybe I should just wait for that.
* Is there some way of doing what I'm trying to do already I'm unaware of?  The InPlace option to Quadratic interpolation hints at copy-free possibilities... but it seems more akin to scipy ndimage's interpolation's prefiltering... and even if it preserved the sharing, then there's the problem of how get only one worker to do it.  Not sure if I've just not quite got the right options to `interpolate`

Thanks for any suggestions or solutions.

**Comment by timholy** [comment]
It's been ages since I've worked on Interpolations, but if memory serves there are `interpolate!` and `prefilter!` functions. Using those perhaps you could preallocate a `SharedArray` for the padded version?

**Comment by timday** [comment]
Aha... I hadn't noticed the '!' functions... that looks promising... will give them a try soon.

**Comment by timday** [comment]
OK the pling is the thing... an `interpolate!` version works great.  I can run this with as many processes as I want:

```
using Interpolations

# Function to compute via interpolator
function test(volume)

  image=SharedArray(Float32,(512,512))

  sampler=interpolate!(
    volume,
    Interpolations.BSpline(Interpolations.Linear()),
    Interpolations.OnGrid()
  )

  @sync @parallel for i=1:512*512
    x,y=ind2sub((512,512),i)
    image[x,y]=sampler[x,y,512]
  end
  sdata(image)
end

# Initialize 1GByte of SharedArray
volume=SharedArray(Float32,(512,512,1024))  # 1 GByte of shared data
volume[:,:,:]=rand(Float32,(512,512,1024))

println(mean(test(volume)))
```

Thanks for the pointer!  I'll close this issue.

**Comment by timholy** [comment]
Great, glad it worked!
