### ISSUE TITLE
Interploation of Float32 array returns Float64

### ISSUE THREAD

**Issue by mauro3** [tlycken/Interpolations.jl#117]
```
julia> typeof(interpolate((1.0:2, 1.0:2), rand(Float32,2,2), Interpolations.Gridded(Linear()) )[1.5,1.5])
Float64
```
Not the end of the world but maybe fixable?

Note that it works for BigFloats:
```
julia> typeof(interpolate((1.0:2, 1.0:2), convert(Matrix{BigFloat},rand(2,2)), Interpolations.Gridded(Linear()) )[1.5,1.5])
BigFloat
```

**Comment by timholy** [comment]
Try using `Float32` for your interpolation points, too.

**Comment by mauro3** [comment]
Ok, I'll try that.  No:
```
julia> typeof(interpolate((1f0:2, 1f0:2), rand(Float32,2,2), Interpolations.Gridded(Linear()) )[1.5,1.5])
Float64
```
But anyway, isn't there also a case for having the knots a different datatype to the values?

**Comment by timholy** [comment]
I meant the evaluation points:
```jl
julia> typeof(interpolate((1f0:2, 1f0:2), rand(Float32,2,2), Interpolations.Gridded(Linear()) )[1.5f0,1.5f0])
Float32
```
This is how it should work: for example, for linear interpolation at a fraction `Δx` between two grid points, we have `Δx*a[i] + (1-Δx)*a[i+1]`. The type of `Δx` is relevant too.

**Comment by mauro3** [comment]
Thanks & fair enough.  From my naive perspective, it could also make sense to always return the type of the interpolated array, which would necessitate conversion in this case.

Feel free to close this.

**Comment by timholy** [comment]
> it could also make sense to always return the type of the interpolated array, which would necessitate conversion in this case.

That's strictly less powerful; for example, you can compute derivatives of interpolants by evaluating at positions expressed as `DualNumber`s. Indeed we make use of that in checking that `gradient` is actually returning the right answer.

**Comment by mauro3** [comment]
Sorry to necromance this.  I'm trying to interpolate a mask (i.e. Bools) onto a different grid using `Constant`.  Is there a reason to not return a Bool for this?  Also, note that the return-type is different depending on the query points (single point vs several):
```
julia> typeof(interpolate((1.0:2, 1.0:2), rand(Bool,2,2), Interpolations.Gridded(Constant()) )[1.5,1.5])
Int64

julia> typeof(interpolate((1.0:2, 1.0:2), rand(Bool,2,2), Interpolations.Gridded(Constant()) )[[1.5,1.5],[1.5,2.0]])
Array{Float64,2}
```
