### ISSUE TITLE
Uneven Interpolation? 

### ISSUE THREAD

**Issue by huckl3b3rry87** [tlycken/Interpolations.jl#125]
I see this old issue https://github.com/JuliaLang/julia/issues/2557

Has this been resolved in Interpolations.jl? 

I.e., can we do unevenly spaced 1D interpolation

**Comment by huckl3b3rry87** [comment]
use  Dierckx.jl

**Comment by spencerlyon2** [comment]
Sorry, just seeing this.

You can do `itp = interpolate(x, y, Gridded(Linear()))` for uneven data.
