### ISSUE TITLE
Specifying the output type of an interpolation object

### ISSUE THREAD

**Issue by tlycken** [tlycken/Interpolations.jl#17]
One of the issues with Grid.jl was that it's hard to specify what type the interpolation object should return - Interpolations.jl should be able to do better if we want it to be easily usable with any number type.

I'm leaning toward an interface with an optional first type argument, that specifies the output type, similar to what `round` and friends do in 0.4:

```
julia> itp = Interpolation(Float64, 1:10, Linear(OnGrid()), ExtrapNaN())

julia> typeof(itp[3.2])
Float64
```

Of course, we need to provide some sensible default, and there are a couple of options:

* Use the element type of the input array, i.e. `Interpolation(A, config...) = Interpolation(eltype(A), A, config...)`
  Pros:
    - very predictable for the end user; effectively, `eltype(Interpolation(A,...)) == eltype(A)`

  Cons:
     - will have the same problems as Grid.jl, especially for integer inputs (but these are avoided if the user explicitly sets a type)
     - we have to `convert` each return value, so there must be a conversion defined from whatever our calculations promote to, to the return type.

* Use use some sensible promotion result, e.g. `promote_type(eltype(A), Float64, typeof(x)...)` (where the `Float64` is from the literals in the prefiltering step - we might be able to avoid those, if we can require a `convert` method for converting floats to `eltype(A)`)

  Pros:
    - very similar to what we do today
    - won't require anything extra from the user to work with integers, e.g. `itp = Interpolation(1:10, ...)`

  Cons:
    - might be difficult to get it right, since there are lots of places where numbers enter the calculations
    - might seem unpredictable to the user, especially since e.g. `promote_type(Rational{Int}, Float64) == Float64` will make us return floats instead of rationals for `Interpolation(A::Array{T<:Rational}, ...)`

I honestly don't know what's best here, but before we start implementing this, we need some sort of decisions on:

* What should the API look like? (Is the above suggestion good or ugly?)
* How should we choose a default?

**Comment by tlycken** [comment]
Thinking another round on it after asking for help in #19 just now, I'm starting to believe converting to `TCoefs` isn't such a good idea. For "duck type-based multivalued interpolation", we want to allow e.g. `TCoefs<:AbstractArray`, but indexing with an array doesn't make sense. 

I think we need to do some more bikeshedding...

Given the methods defined on `AbstractArray`, I think it's safe to assume that an index should be a `Real`. (Cases with other coordinate systems, including e.g. unitful quantities, will have to be handled with a wrapper similar to `CoordInterpGrid`.) I would also like to make/keep it so that `eltype(itp)` should be as close to `eltype(A)` as possible given an interpolation object `itp` constructed from an array `A` - thus, if A is `Array{Rational{Int}}`, then `typeof(itp[...]) == Rational{Int}` too. (In some cases this doesn't make sense - e.g. if `eltype(A) == Int`, I think `eltype(itp)` should be `Float64`.)

To make it so, we need to be careful about types in the following parts of the code:

* When calculating `ix_d` based on `x_d` (e.g. [here](https://github.com/tlycken/Interpolations.jl/blob/6daa6f71626576ceafaaf995fba1c57f7e3c93c3/src/linear.jl#L8)). This involves somehow rounding the (`Real`) index `x_d`.
* When calculating `fx_d` based on `x_d` and `ix_d` (e.g. [here](https://github.com/tlycken/Interpolations.jl/blob/6daa6f71626576ceafaaf995fba1c57f7e3c93c3/src/linear.jl#L10)). This involves subtraction between `ix_d` and `x_d`.
* When calculating the coefficients `c_d`, `cm_d`, `cp_d` etc used in the interpolation expression. For some interpolation types (e.g. [linear](https://github.com/tlycken/Interpolations.jl/blob/6daa6f71626576ceafaaf995fba1c57f7e3c93c3/src/linear.jl#L22)) this only involves subtraction between 1 and `fx_d`, but for higher orders (e.g. [here](https://github.com/tlycken/Interpolations.jl/blob/6daa6f71626576ceafaaf995fba1c57f7e3c93c3/src/quadratic.jl#L39) for quadratic) it also involves non-one literals and multiplication; this is probably one of the places we have to be the most careful.
* When calculating the interpolated value (e.g. [here](https://github.com/tlycken/Interpolations.jl/blob/6daa6f71626576ceafaaf995fba1c57f7e3c93c3/src/linear.jl#L42)). This involves multiplication between `c_d` and an element of type `TCoefs`, possibly several times.

Given the facts above, it seems that we have to make yet another separation between types, and add another type parameter to the interpolation object; a `TIndex<:Real`, to which we convert all indices. The contract would then be that `typeof(itp[x]) == typeof(one(TIndex)^ndims(A) * one(TCoefs))`, i.e. that the return type is the result of promotion between the indexing type and the coefficient type under the operations required to interpolate.

I think we can still get away with having the user specify only one (optional) type argument, namely `TIndex`. We could default `TIndex` to `Float64`, and make special cases for types in base that don't behave well under promotion with `Float64`, i.e. `Rational` and `Float32` (and possibly `Float16`, although I've understood that `Float16` is just a storage type, so maybe not).

Does this seem like a reasonable approach?

**Comment by timholy** [comment]
I realize I caused a terminology confusion: I forgot there's a field called `coefs` that indeed must have multivalued type. What I meant by `Tcoef` is basically what you're calling `TIndex` now. I guess I should have called those "weights" or something.

So yes, this is a reasonable approach, with one possible caveat which I may try a PR to fix.

**Comment by timholy** [comment]
Now I'm beginning to wonder if we want to always use duck-typing, and just preserve whatever the user passes as an index. That would mean we can't make `Interpolation` a subtype of `AbstractArray`, however.

**Comment by timholy** [comment]
Here's the best reason to consider this:
```julia
julia> function qinterp1(A, x)
           ix = round(Int, real(x))
           xf = x-ix
           cm = 1//2 * (xf-1//2)^2
           c = 3//4 - xf^2
           cp = 1//2 * (xf+1//2)^2
           cm*A[ix-1] + c*A[ix] + cp*A[ix+1]
       end

julia> A = [(3.8-x)^2+2 for x = 1:10]
10-element Array{Float64,1}:
  9.84
  5.24
  2.64
  2.04
  3.44
  6.84
 12.24
 19.64
 29.04
 40.44

julia> qinterp1(A, 2.1)
5.139999999999999

julia> using DualNumbers

julia> qinterp1(A, dual(2.1,1))
5.139999999999999 - 3.4du

julia> dx = sqrt(eps())
1.4901161193847656e-8

julia> (qinterp1(A, 2.1+dx)-qinterp1(A, 2.1-dx))/(2*dx)  # finite-difference estimate of the gradient
-3.4000000059604645
```
DualNumbers allows people to check derivatives of any functions that use interpolations internally; it's much higher-precision than finite differencing, and oh-so-much-easier to use. (Related: I notice the gradient tests are very "sloppy" with tolerances of e.g., `abs(0.1*f(x))`; using DualNumbers for writing tests of this package would be an easy way to test with much higher precision.)

Amplifying on my comment above: since the output type of `getindex` would no longer be something that can be determined at the time the `Interpolation` type is constructed, it seems that `Interpolation` can't be a subtype of `AbstractArray`.

**Comment by tlycken** [comment]
A compelling argument indeed. What benefits do we have from subtyping `AbstractArray`, that we'd lose if we didn't?

Another argument to drop `Interpolation <: AbstractArray` is that this relation makes `Interpolation{T,1} <: AbstractVector`, but there are a lot of methods taking `AbstractVectors` which really expect iterables with a finite number of elements, which interpolations sort-of have (we know their size) but you could also argue that they have an infinite number. In other words, I'm not sure that `AbstractInterpolation{T,N}` actually *wants* to fulfill the contract that  `AbstractArray{T,N}` wants to define.

**Comment by timholy** [comment]
The first thing that occurs to me is the loss of the ability to create `SubArray`s from `Interpolation` objects. Although perhaps we could loosen the typing on `SubArray`, making no restrictions on the parent type.

**Comment by tlycken** [comment]
Reading about `SubArray`s [here](http://docs.julialang.org/en/release-0.3/manual/arrays/?highlight=subarray#implementation), it seems like loosening the typing might be risky; to make them work with `Interpolations`, IIUC they cannot be `<:AbstractArray` either. I feel that might break a lot of calling code... but if it's workable, that's cool. Supporting `SubArray` is possibly not the most important aspect of `Interpolation`s either.

**Comment by timholy** [comment]
You may want to follow any discussion in https://github.com/JuliaLang/julia/issues/9586.

**Comment by tlycken** [comment]
Thanks for the cross-reference; I've subscribed. The results should be interesting =)
