### ISSUE TITLE
Startup times & stagedfunctions

### ISSUE THREAD

**Issue by timholy** [tlycken/Interpolations.jl#21]
The load time for the package are fairly long, largely because lots of methods need to be generated. The load time could probably be drastically shortened using stagedfunctions, which allow the methods to be generated on-demand.

If you get to the point where you are ready to switch your development to 0.4, I will gladly convert things over to using stagedfunctions.

**Comment by tlycken** [comment]
I have been thinking a lot about this too - to the point where I've started writing, then discarded, a post to julia-users asking where the documentation for `stagedfunction`s is, if it exists, and whether the feature is ready enough for some real-use-case tire-kicking. I have put off dropping 0.3 support until Julia master is moved to 0.4-pre status ([by the end of the month?](https://groups.google.com/d/msg/julia-users/LHHNRIsJn74/MfUUAAP2lWIJ)). When we do move to `stagedfunction`s, I'd be happy to do at least some of the converting work myself - I don't know when next I'll get such a good use-case to try it out on =)

In the meantime, my workaround when testing various things has been to comment out most options for `IT` and `EB` in the loops generating `getindex` and `gradient` methods, which pulls down the load time to an acceptable second or so for one or two cases.

But yes, we should definitely do this.

**Comment by timholy** [comment]
I'm being begged to write stagedfunction documentation in multiple julia issues already.

**Comment by mbauman** [comment]
Bump! Now that `@ngenerate` has been removed from Julia, Iterations is broken on 0.4… even with Compat.jl since it uses a private ngenerate function.

**Comment by tlycken** [comment]
@mbauman Thanks for the notification! I've been swamped by other stuff (work, mostly...) lately, so I haven't been able to put as much time as I'd like into this project. I'll see when I can get to it next, but I won't complain if anyone else gets to it before I do.

**Comment by timholy** [comment]
I likewise plan to get to this if no one beats me to it, but it won't be before Wednesday.

**Comment by timholy** [comment]
Fixed by 6da1207df40329150706d354ec72346f02eda4c4
