### ISSUE TITLE
Something equivalent to CoordInterpGrid

### ISSUE THREAD

**Issue by tlycken** [tlycken/Interpolations.jl#25]
In order to reach feature parity with Grid.jl, we need something like `CoordInterpGrid`, that re-scales the interpolation indices to some other coordinate system. This could probably be implemented very similarly to `CoordInterpGrid`, since the underlying interpolation interface is very similar.

**Comment by gaabriel** [comment]
Yes, this, please!

**Comment by tlycken** [comment]
@gaabriel, I'm sorry this has taken so long, but I've now started working on implementing this in #47. What do you think of that API? Is there some specific functionality that you would have use for, that the suggested solution does not cover?
