### ISSUE TITLE
Gridded Interpolation Seems broken

### ISSUE THREAD

**Issue by SloanLindsey** [tlycken/Interpolations.jl#65]
I am trying to use the gridded interpolation for a look up table with a linear and logspaced axis, however I'm not getting past the initial documentation tests.
A = rand(8,20)
itp = interpolate(A, Gridded{Linear})
yields the following error:

ERROR: MethodError: `interpolate` has no method matching interpolate(::Array{Float64,2}, ::Type{Interpolations.Gridded{Interpolations.Linear
}})
Closest candidates are:
  interpolate{TWeights,TCoefs,IT<:Union{Interpolations.BSpline{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.BSpline{D<:Interpola
tions.Degree{N}}}}},GT<:Union{Interpolations.GridType,Tuple{Vararg{Interpolations.GridType}}}}(::Type{TWeights}, ::Type{TCoefs}, ::Any, ::Ty
pe{IT<:Union{Interpolations.BSpline{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.BSpline{D<:Interpolations.Degree{N}}}}}}, ::Typ
e{GT<:Union{Interpolations.GridType,Tuple{Vararg{Interpolations.GridType}}}})
  interpolate{IT<:Union{Interpolations.BSpline{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.BSpline{D<:Interpolations.Degree{N}}
}}},GT<:Union{Interpolations.GridType,Tuple{Vararg{Interpolations.GridType}}}}(::AbstractArray{T,N}, ::Type{IT<:Union{Interpolations.BSpline
{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.BSpline{D<:Interpolations.Degree{N}}}}}}, ::Type{GT<:Union{Interpolations.GridType
,Tuple{Vararg{Interpolations.GridType}}}})
  interpolate{TWeights,TCoefs,Tel,N,IT<:Union{Interpolations.Gridded{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.Gridded{D<:Int
erpolations.Degree{N}}}}}}(::Type{TWeights}, ::Type{TCoefs}, ::NTuple{N,Union{AbstractArray{T,1},Tuple}}, ::AbstractArray{Tel,N}, ::Type{IT<
:Union{Interpolations.Gridded{D<:Interpolations.Degree{N}},Tuple{Vararg{Interpolations.Gridded{D<:Interpolations.Degree{N}}}}}})

I'm currently trying to discover the proper syntax, but the intro documentation on the front page does not work.
Can someone help me out in the correct call syntax?

Thanks,
Sloan

**Comment by SloanLindsey** [comment]
I should also point out that the issue occurs on 0.40-rc1

**Comment by SloanLindsey** [comment]
Upon reading more deeply into the issues I found an example of the call. 
As opposed to the syntax defined on the intro page,
one should really do:
itp = interpolate( (x_knots, y_knots), A, Tuple{Gridded{Linear}, Gridded{Linear}})
there is no option for leaving out the knots as suggested on the start page (and why should there be how can you define the locations otherwise) and you must define the Tuple for each dimension.

**Comment by timholy** [comment]
This is what I was worried about with the documentation change in #61. Would you like to try to improve the documentation to make it clearer? (You can just click on the README.md file, then on the little pencil icon, and start editing. Your changes will be inspected by @tlycken and/or me before they get merged, so don't worry about messing anything up.)

**Comment by SloanLindsey** [comment]
Sure,
I'll do some playing around and post the updates.
