### ISSUE TITLE
generated function

### ISSUE THREAD

**Issue by matthieugomez** [tlycken/Interpolations.jl#77]
Not an issue, but, reading the code, I was just wondering why `size` was a generated function [here](https://github.com/tlycken/Interpolations.jl/blob/master/src/b-splines/b-splines.jl#L46)

```julia
@generated function size{T,N,TCoefs,IT,GT,pad}(itp::BSplineInterpolation{T,N,TCoefs,IT,GT,pad}, d)
    quote
        d <= $N ? size(itp.coefs, d) - 2*padextract($pad, d) : 1
    end
end
```
Isn't it exactly equivalent to this version?
```julia
function size{T,N,TCoefs,IT,GT,pad}(itp::BSplineInterpolation{T,N,TCoefs,IT,GT,pad}, d)
    d <= N ? size(itp.coefs, d) - 2*padextract(pad, d) : 1
end
```

**Comment by timholy** [comment]
Yeah, it probably is. Probably an editing mistake, can you submit a PR?

**Comment by tlycken** [comment]
Github's hooks didn't pick that up, but this was fixed in 22bf138.

**Comment by timholy** [comment]
To make it happen automatically, just put `fixes #77` in the commit message somewhere.

**Comment by tlycken** [comment]
Yeah, the PR had `solves issue #77` in it, so I thought that would be enough, but I guess the "issue" in between confused it :)

**Comment by timholy** [comment]
It's a simple-minded little bot :smile:
