### ISSUE TITLE
Type Issues - 'convert' has no method matching 'convert'

### ISSUE THREAD

**Issue by pazzo83** [tlycken/Interpolations.jl#80]
I've seen this with some of my code as well in v0.4, but right now I can't run any of the examples from the readme:

```
ERROR: MethodError: `convert` has no method matching convert(::Type{Interpolatio
ns.Gridded{D<:Interpolations.Degree{N}}}, ::Interpolations.Linear)
This may have arisen from a call to the constructor Interpolations.Gridded{D<:In
terpolations.Degree{N}}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
  Interpolations.Gridded{D<:Interpolations.Degree{N}}(::Type{D<:Interpolations.D
egree{N}})
 in call at essentials.jl:56
```

This is after I ran this example:
```
A = rand(8,20)
knots = ([x^2 for x = 1:8], [0.2y for y = 1:20])
itp = interpolate(knots, A, Gridded(Linear()))
```

Any thoughts?

**Comment by timholy** [comment]
My guess is that you're following the documentation for master but not running master. (This is not your fault; ideally we could update the documentation without it appearing on the "home page" until we tag a new version.)

Does `Pkg.checkout("Interpolations")` fix it for you?

**Comment by tlycken** [comment]
A tag is probably due, to avoid more people running into the same problem.

`Pkg.update()` should suffice once https://github.com/JuliaLang/METADATA.jl/pull/3755 merges.

**Comment by pazzo83** [comment]
Thanks guys, works perfectly now!  I had forgotten that a master checkout might have had additional changes beyond the latest tag.

Thanks!!
