### ISSUE TITLE
Exporting Change with @everywhere

### ISSUE THREAD

**Issue by SloanLindsey** [tlycken/Interpolations.jl#81]
I'm not sure where this problem is occurring but it seems localized to Interpolations. 
I'm using pmap to execute numerous sub-tasks and I use @everwhere include("task_execution.jl").
Two places in task_execution in different sub-files an interpolator is created by calling 
```jl
using Interpolations
```
and then going through the specification. This has worked for a couple of days, but I restarted my repl and ran Pkg.update() and now something weird is happening.

I get the following warning for each of the worker tasks
WARNING: replacing module Interpolations
WARNING: replacing module Interpolations

and then finally I get this: 
ERROR: LoadError: On worker 2:
...,LoadError("C:\\dev\\julia\\.julia\\v0.4\\Interpolations\\src\\Interpolations.jl",88,LoadError("C:\\dev\\julia\\.julia\\v0.4\\Interpolations\\src\\scaling/scaling.jl",161,UndefVarError(:Quadratic)))))

 in include_string at loading.jl:233
 in include_from_node1 at loading.jl:274
 in include_string at loading.jl:233
 in include_from_node1 at loading.jl:274
 in require at loading.jl:210
 in include_string at loading.jl:233
 in include_from_node1 at loading.jl:274
 in include_string at loading.jl:233
 in include_from_node1 at loading.jl:274
 in eval at sysimg.jl:14
 in anonymous at multi.jl:1350
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:68
 in remotecall_fetch at multi.jl:731

...and 3 other exceptions.

 in sync_end at task.jl:414
 in anonymous at multi.jl:1361
 in include at boot.jl:260
 in include_from_node1 at loading.jl:271

Running the load again changes the file that's missing.
Hopefully this is enough to identify what is happening. In the mean time I will work on making a dedicated test case.

**Comment by SloanLindsey** [comment]
I have built a minimal test case to demonstrate.

```jl
#work_file.jl

using Interpolations

function run_demo2D(counter)
  println("This is task: $counter")
  A = rand(8,20)
  knots = ([x^2 for x = 1:8], [0.2y for y = 1:20])
  itp = interpolate(knots, A, Gridded(Linear()))
  itp[4,1.2]  # approximately A[2,6]
end
```

```jl
#calling_file.jl
@everywhere include("work_file.jl")

function test_things(some_number)
  run_vector = collect(1:some_number)
  results = pmap(run_demo2D, run_vector)
  println("$results")
end
```

then from the repl started with -p 4 (4 worker threads)

```jl
julia> include("calling_file.jl")
WARNING: replacing module Interpolations
WARNING: replacing module Interpolations
WARNING: replacing module Interpolations
WARNING: replacing module Interpolations
ERROR: LoadError: On worker 5:
LoadError: LoadError: LoadError: SystemError: opening file C:\dev\julia\.julia\v0.4\Interpolations\src\extrapolation\prefiltering.jl: No suc
h file or directory
 in open at iostream.jl:90
 in open at iostream.jl:112
 in readall at io.jl:262
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:63
 in remotecall_fetch at multi.jl:731
 in remotecall_fetch at multi.jl:734
 in include_from_node1 at loading.jl:307
 in include_string at loading.jl:266
 in include_from_node1 at loading.jl:307
 in include_string at loading.jl:266
 in include_from_node1 at loading.jl:307
 in require at loading.jl:243
 in include_string at loading.jl:266
 in include_from_node1 at loading.jl:307
 in eval at sysimg.jl:14
 in anonymous at multi.jl:1350
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:63
while loading C:\dev\julia\.julia\v0.4\Interpolations\src\extrapolation/extrapolation.jl, in expression starting on line 80
while loading C:\dev\julia\.julia\v0.4\Interpolations\src\Interpolations.jl, in expression starting on line 65
while loading C:\dev\parallel_interpolations_demo\work_file.jl, in expression starting on line 2
 in remotecall_fetch at multi.jl:731
 in sync_end at task.jl:413
 in anonymous at multi.jl:1361
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\dev\parallel_interpolations_demo\calling_file.jl, in expression starting on line 1
```

Of course I cannot seem to duplicate the functioning case when everything was working. Is there an elegant way to backlevel to earlier package versions?  I know for sure that the old Tuple{} syntax was in use until I updated today.

Thanks,
Sloan

**Comment by SloanLindsey** [comment]
I have narrowed it down to Interpolations. When I do the same test using Roots and fzero everything functions as intended.

**Comment by tlycken** [comment]
I can reproduce this on 0.4; however, to me the search path for `Interpolations` files isn't even nearly correct unless I first `@everywhere ENV["HOME"] = <path to my home dir>`. However, even after doing that, I get similar error messages (but for a different file in the library).

@timholy Do you have any idea what this might be?

**Comment by SloanLindsey** [comment]
Yeah, sorry I failed to mention that. The file that throws the error seems
to move around and is often not even a piece of interpolations that I'm
using. E.G. I get missing quadratic.jl but I only use gridded linear.
-Sloan

**Comment by timholy** [comment]
There are some weird things about having multiple workers that stem from module conflicts; all those "replacing" are worrisome.

So I didn't even try your demo, I went straight to this:
```jl
julia> using Interpolations

# Work around https://github.com/JuliaLang/julia/issues/9245
julia> for p in workers()
           remotecall_fetch(p, eval, :(using Interpolations))
       end
                                                                                                                                                                                                                                                                               
julia> @everywhere include("/tmp/work_file.jl")
                                                                                                                                                                                                                                                                               
julia> function test_things(some_number)
         run_vector = collect(1:some_number)
         results = pmap(run_demo2D, run_vector)
         println("$results")
       end
test_things (generic function with 1 method)

julia> test_things(8)
        From worker 2:  This is task: 1
        From worker 5:  This is task: 4
        From worker 4:  This is task: 3
        From worker 3:  This is task: 2
        From worker 5:  This is task: 5
        From worker 2:  This is task: 6
        From worker 4:  This is task: 7
        From worker 3:  This is task: 8
Any[0.39778033365858445,0.7525284467103295,0.2041740762657227,0.4440123422721362,0.8178983426464757,0.6379167351368877,0.9319793831607008,0.9442503465962125]
```
and it worked fine. Note that I took `using Interpolations` out of `work_file`, because I didn't want it inside that `@everywhere` (which is the source of your "replacing" warnings).

Someone really needs to fix https://github.com/JuliaLang/julia/issues/9245, it's really annoying. Maybe I'll get to it myself, but help from other would be very welcome.

**Comment by timholy** [comment]
Since I don't think this is specific to Interpolations, I suggest it can be closed. Will wait for @SloanLindsey  to confirm.

**Comment by SloanLindsey** [comment]
@timholy, I guess, but the behavior was different a few releases ago. I'm not sure what changed (which was my real question) Can we leave this open for a few more hours so I can test your work-around?

**Comment by timholy** [comment]
It can stay open for weeks, if need be!

**Comment by SloanLindsey** [comment]
@timholy 

I made the prescribed changes to calling_file.jl and work_file.jl

```jl
#calling_file.jl
using Interpolations
for p in workers()
  remotecall_fetch(p, eval, :(using Interpolations))
end

@everywhere include("work_file.jl")

function test_things(some_number)
  run_vector = collect(1:some_number)
  results = pmap(run_demo2D, run_vector)
  println("$results")
end

function test_roots(some_number)
  run_vector = collect(1:some_number)
  results = pmap(run_Roots_demo, run_vector)
  println("$results")
end

```

Now I compile fine but I get and UndefVarError on execution:
Any[RemoteException(2,CapturedException(UndefVarError(:interpolate),Any[(:run_demo2D,symbol("C:\\dev\\parallel_interpolations_demo\\work_fil
e.jl"),9,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symbol(""),-1,1),(:run_work_thunk,symbol("multi.jl"),645,symbol(""),-1,1),(:ano
nymous,symbol("multi.jl"),892,symbol("task.jl"),63,1)])),RemoteException(3,CapturedException(UndefVarError(:interpolate),Any[(:run_demo2D,sy
mbol("C:\\dev\\parallel_interpolations_demo\\work_file.jl"),9,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symbol(""),-1,1),(:run_wor
k_thunk,symbol("multi.jl"),645,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symbol("task.jl"),63,1)])),RemoteException(4,CapturedExce
ption(UndefVarError(:interpolate),Any[(:run_demo2D,symbol("C:\\dev\\parallel_interpolations_demo\\work_file.jl"),9,symbol(""),-1,1),(:anonym
ous,symbol("multi.jl"),892,symbol(""),-1,1),(:run_work_thunk,symbol("multi.jl"),645,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symb
ol("task.jl"),63,1)])),RemoteException(5,CapturedException(UndefVarError(:interpolate),Any[(:run_demo2D,symbol("C:\\dev\\parallel_interpolat
ions_demo\\work_file.jl"),9,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symbol(""),-1,1),(:run_work_thunk,symbol("multi.jl"),645,sym
bol(""),-1,1),(:anonymous,symbol("multi.jl"),892,symbol("task.jl"),63,1)]))]

Therefore it seems like the multi-file issue is what is causing problems. Any hints?
(I'm presently wading into the referenced issue with Julia)
-Sloan

**Comment by timholy** [comment]
Somehow the worker doesn't know about `interpolate`. I'm wondering if you're now being bitten by https://github.com/JuliaLang/julia/issues/3674.

Can you start a fresh julia session, paste the contents of `calling_file.jl` into the REPL, and show us what output it produces?

**Comment by SloanLindsey** [comment]
So now things seem to be working? I had some strange version or cache bug that cleared itself. I'm now testing if I can extend the load work around to my real code base.

**Comment by SloanLindsey** [comment]
Ok! We can close, but this will be available for searching. Thanks again @timholy! the explicit worker load did the trick and functions to control the scope of the call. 
As to my other question about back-leveling to find when the bug cropped up:
https://github.com/JuliaLang/julia/issues/4288
is a useful post. 
Once again, thanks @timholy .
I haven't tracked down where and when in the code the bug cropped up and the explicit loading becomes necessary, I think its between Interpolations versions 0.1.0 and 0.2.0, but the work around is functional as is.

**Comment by timholy** [comment]
Glad it's working for you.
