### ISSUE TITLE
how do you deal with multidimensional problems?

### ISSUE THREAD

**Issue by floswald** [tlycken/Interpolations.jl#91]
Hi there,
just wanted to ask how you interpolate a 3D problem, for example, in the Quadratic BSpline case. Do you take the tensor product of the univariate Spline basis functions in each dimension? I couldn't find it in the code. I'd like to talk about this package in a class I'm teaching, so I need to know a bit more.

thanks!

**Comment by tlycken** [comment]
Yes, that is the basic idea. The introductory sections of [this paper](http://bigwww.epfl.ch/publications/thevenaz0002.pdf) (referenced in the document under `doc/latex` in this repo) are a good read.

It's also instructive to look at the output of the following code for various dimensions:

```
using Interpolations, Base.Cartesian
macroexpand(Interpolations.index_gen(typeof(BSpline(Quadratic(Flat()))), 1))
```

Try that, then change the dimension to 2 and 3 etc to see how the actual interpolation is implemented. You'll get an expression consisting of variables on the form `cx_d`, where `x` indicates a step along the current dimension `d` (e.g. `m` for `-1`, `p` for `+1`), as well as indexing expressions into `itp.coefs`, which is the data to be interpolated (with the pre-filter described in the paper applied already).

**Comment by floswald** [comment]
Excellent, I see. So you place the data on the vertices of the hypercube to
compute the coefficients, and then in `get_index[x]` you compute some form
of linear combination of basis functions, depending on the segment that `x`
comes to lie in?
It is dawning on me that I did hardcode all of this in ApproXD.jl. :-/

**Comment by tlycken** [comment]
Yes, exactly.

And it's not too late to make ApproXD.jl use Interpolations.jl instead ;)
